openapi: "3.0.3"

info:
  title: "sample api"
  description: |
    # Features
    - Get reviews
    - Post reviews
  termsOfService: "https://kokokoko.com/terms/"
  contact:
    name: "Customer Support"
    url: "https://kokokoko.com/support/"
    email: "support-desk@kokokoko.com"
  license:
    name: "MIT License"
    url: "https://opensource.org/license/MIT"
  version: "1.0.0"

paths: {}